functions
```{r}
length(linkedin)
head(linkedin,2)
tail(linkedin,2)

help("mean")

```

use a function

```{r}
avg_li <- mean(x=linkedin)
avg_li
sum(linkedin)
abs(linkedin)

```

write your own function
```{r}

pow_two <- function(arg){
  arg **2
}

pow_two(2)

sum_abs <- function(arg1,arg2){
  abs(arg1) + abs(arg2)
}

sum_abs(-2,3)

hello <- function(){
  print("Hi there")
  return(TRUE)
}

hello()

pow_two <- function(x,print_info=TRUE){
  y <- x^2
  if(print_info){
    print(paste(x,"to the power two equals",y))
  }
  return(y)
}

pow_two(3)

interpret <- function(num_views){
  if(num_views > 15){
    print("you are popular")
    return(num_views)
  }else{
    print("try to be visible")
    return(0)
  }
}

interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  count <- 0
  for(v in views){
    count <- count + interpret(v)
  }
  if(return_sum){
    return(count)
  }else{
    return(NULL)
  }
}

interpret_all(linkedin)

```

install package
```{r}
install.packages("ggplot2")
```

```{r}
library(ggplot2)
mtcars

qplot(mtcars $wt, mtcars $hp)


```
Familia apply

lapply

```{r}
piooners <- c("GAUSS:1777","BAYES:1702","PASCAL:1623","PEARSON:18:57")

split_match <- strsplit(piooners, split = ":")
split_match
split_low <- lapply(split_match, tolower)
split_low

select_first <- function(x){
  x[1]
}

names <- lapply(split_low, select_first)

select_second <- function(x){
  x[2]
}

years <- lapply(split_low, select_second)


```


lapply and anonymous functions
```{r}

split_low
names <- lapply(split_low, function(x){x[1]})
years <- lapply(split_low, function(x){x[2]})


```
use lapply with additional arguments
```{r}

select_el <- function(x,index){
  x[index]  
}

select_el(split_low,1)

names <- lapply(split_low, select_el, 1)
years <- lapply(split_low, select_el, 2)

```

sapply

```{r}

names <- sapply(split_low, select_el,1)

extreme_avg <- function(x){
  (min(x) + max(x))/2
}

vec1 <- c(3,8,7,6)
vec2 <- c(8,8,7,2)
vec3 <- c(10,1,11,6)

temp <- list(vec1,vec2,vec3)

sapply(linkedin, extreme_avg)
lapply(linkedin, extreme_avg)


```
vapply

```{r}

basics <- function(x){
  c(min = min(x), mean = mean(x), max = max(x))
}

temp
vapply(temp,basics,numeric(3))

```
Math utilities
```{r}

errors <- c(1.9,-2.6,4.0,-9.5,-3.4,7.3)
print(sum(abs(round(errors))))

```

